
- name: Test TF CLI
  hosts: localhost
  tasks:
    - name: Template main.tf
      ansible.builtin.template:
        src: ./tfe_project/main.tf.j2
        dest: ./tfe_project/main.tf
        mode: '0644'
      delegate_to: localhost

    - name: TF deploy of a service
      cloud.terraform.terraform:
        project_path: './tfe_project'
        state: present
        force_init: true