
- name: Test TF CLI
  hosts: localhost
  tasks:
    - name: Ensure .terraform.d directory exists
      file:
        path: "{{ lookup('env', 'HOME') }}/.terraform.d"
        state: directory
        mode: '0755'

    - name: Template credentials.tfrc.json
      ansible.builtin.template:
        src: ./tfe_project/credentials.tfrc.json.j2
        dest: "~/.terraform.d/credentials.tfrc.json"
        mode: '0600'

    - name: Template main.tf
      ansible.builtin.template:
        src: ./tfe_project/main.tf.j2
        dest: ./tfe_project/main.tf
        mode: '0644'
      delegate_to: localhost

    - name: TF deploy of a service
      cloud.terraform.terraform:
        project_path: './tfe_project'
        state: present
        force_init: true
